name: "Lerna Version and Publish"
description: "Update package versions with lerna and create a pull request. Publish packages when the PR is merged."
inputs:
  github-token:
    description: "GitHub token"
    required: true
  version-command:
    description: "Command to update package versions"
    required: true
  publish-command:
    description: "Command to publish packages"
    required: true
  commit-msg:
    description: "Commit message"
    default: "Update package versions"
    required: false
  commit-title:
    description: "Pull request title"
    default: "Update package versions"
    required: false
  branch-name:
    description: "Branch name for version updates"
    default: "version-update"
    required: false
  user-name:
    description: "Git user name"
    default: "GitHub Action"
    required: false
  user-email:
    description: "Git user email"
    default: "action@github.com"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
